import { ReactNode } from 'react';
import Head from 'next/head';
import styled from '@emotion/styled';
import dynamic from 'next/dynamic';

const StyledMain = styled.main`
  display: flex;
  margin: 40px auto 0;
  flex: 1 0 960px;
  max-width: 960px;
`;

const SidebarWithNoSSR = dynamic(() => import('../Sidebar/Sidebar'), { ssr: false });

export default function MainLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <SidebarWithNoSSR />
        {children}
      </StyledMain>
    </>
  );
}
